In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [5]:
df_path = 'D:\coding\Pune_weather_forcasting\src\data\pune.csv'

In [46]:
df = pd.read_csv(df_path,encoding='utf-8')

df.head()

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2009-01-01 00:00:00,31,13,0.0,11.0,6,1,31,10:17 AM,10:16 PM,...,18,7,0,50,0.0,1013,13,10,59,3
1,2009-01-01 01:00:00,31,13,0.0,11.0,6,1,31,10:17 AM,10:16 PM,...,18,9,0,47,0.0,1013,14,10,57,4
2,2009-01-01 02:00:00,31,13,0.0,11.0,6,1,31,10:17 AM,10:16 PM,...,18,10,0,44,0.0,1013,14,10,55,5
3,2009-01-01 03:00:00,31,13,0.0,11.0,6,1,31,10:17 AM,10:16 PM,...,18,12,0,41,0.0,1013,15,10,54,6
4,2009-01-01 04:00:00,31,13,0.0,11.0,6,1,31,10:17 AM,10:16 PM,...,20,11,1,38,0.0,1014,16,10,68,6

In [11]:
df.describe()

,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,DewPointC,FeelsLikeC,HeatIndexC,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
count,96432.000000,96432.000000,96432.0,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000
mean,30.945495,20.206322,0.0,10.396267,6.134644,3.903248,46.094077,14.870603,26.552006,26.863168,25.854882,13.427773,29.235295,57.868384,0.069972,1009.746744,24.867751,9.483418,206.268179,9.703491
std,4.379970,3.133037,0.0,2.011727,0.932275,3.024399,31.249725,6.320289,4.797706,4.552259,4.926656,6.675652,32.747828,25.447424,0.396050,3.639374,5.031090,1.855224,91.756947,5.346128
min,20.000000,10.000000,0.0,4.100000,4.000000,1.000000,0.000000,-12.000000,12.000000,12.000000,12.000000,0.000000,0.000000,4.000000,0.000000,998.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,18.000000,0.0,8.700000,5.000000,1.000000,18.000000,10.000000,23.000000,25.000000,22.000000,9.000000,2.000000,36.000000,0.000000,1007.000000,22.000000,10.000000,105.000000,6.000000
50%,30.000000,21.000000,0.0,11.200000,6.000000,1.000000,46.000000,16.000000,26.000000,26.000000,25.000000,12.000000,12.000000,58.000000,0.000000,1010.000000,24.000000,10.000000,252.000000,9.000000
75%,34.000000,22.000000,0.0,11.600000,7.000000,7.000000,73.000000,21.000000,29.000000,29.000000,29.000000,17.000000,56.000000,82.000000,0.000000,1013.000000,28.000000,10.000000,276.000000,13.000000
max,42.000000,30.000000,0.0,13.600000,9.000000,10.000000,100.000000,26.000000,49.000000,49.000000,46.000000,55.000000,100.000000,100.000000,19.900000,1021.000000,42.000000,20.000000,360.000000,39.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96432 entries, 0 to 96431
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date_time          96432 non-null  object
 1   maxtempC           96432 non-null  int64
 2   mintempC           96432 non-null  int64
 3   totalSnow_cm       96432 non-null  float64
 4   sunHour            96432 non-null  float64
 5   uvIndex            96432 non-null  int64
 6   uvIndex.1          96432 non-null  int64
 7   moon_illumination  96432 non-null  int64
 8   moonrise           96432 non-null  object
 9   moonset            96432 non-null  object
 10  sunrise            96432 non-null  object
 11  sunset             96432 non-null  object
 12  DewPointC          96432 non-null  int64
 13  FeelsLikeC         96432 non-null  int64
 14  HeatIndexC         96432 non-null  int64
 15  WindChillC         96432 non-null  int64
 16  WindGustKmph       96432 non-null  int64
 17  cloudcover         96432 non-null  int64
 18  humidity           96432 non-null  int64
 19  precipMM           96432 non-null  float64
 20  pressure           96432 non-null  int64
 21  tempC              96432 non-null  int64
 22  visibility         96432 non-null  int64
 23  winddirDegree      96432 non-null  int64
 24  windspeedKmph      96432 non-null  int64
dtypes: float64(3), int64(17), object(5)
memory usage: 18.4+ MB

In [41]:
num_features = df.select_dtypes(include=['int64','float64'])
print(num_features.columns)

Index(['maxtempC', 'mintempC', 'totalSnow_cm', 'sunHour', 'uvIndex',
       'uvIndex.1', 'moon_illumination', 'DewPointC', 'FeelsLikeC',
       'HeatIndexC', 'WindChillC', 'WindGustKmph', 'cloudcover', 'humidity',
       'precipMM', 'pressure', 'tempC', 'visibility', 'winddirDegree',
       'windspeedKmph'],
      dtype='object')

In [49]:
cat_features = df.select_dtypes(include=object).drop(columns=['date_time'])
cat_features.head()

   moonrise   moonset   sunrise    sunset
0  10:17 AM  10:16 PM  07:07 AM  06:09 PM
1  10:17 AM  10:16 PM  07:07 AM  06:09 PM
2  10:17 AM  10:16 PM  07:07 AM  06:09 PM
3  10:17 AM  10:16 PM  07:07 AM  06:09 PM
4  10:17 AM  10:16 PM  07:07 AM  06:09 PM

gonna have to convert these to date_time objects to get numerical data so that we can plot it

In [55]:
for col_name in cat_features.columns:
    no_name = "No " + df[col_name]
    df[col_name] = df[col_name].where(~df[col_name].str.startswith("No "), pd.NA)
    df[col_name] = pd.to_datetime(df[col_name],format = "%I:%M %p",errors="coerce")
    min_name = col_name+"_minutes"
    df[min_name] = df[col_name].dt.hour*60 + df[col_name].dt.minute

TypeError: can only concatenate str (not "DatetimeArray") to str